### ISSUE TITLE
Please create chrome://flags/ links

### ISSUE THREAD

**Issue by noseshimself** [Nu11u5/chromium-flags#1]
to make accessing the flags easier.

**Comment by Nu11u5** [comment]
This was something I tried early on.  Unfortunately it is not possible, for two reasons:

- `chrome://*` URLs are considered "private" and the web browser does not allow webpages to link to them (it spits the error _"Not allowed to load local resource"_ into the console).
- The page is presented using Google Sheets, and the API blocks creating URLs that are not using an http/s schema.

Thanks for the suggestion, though, and being issue #1!
