### ISSUE TITLE
iOS flags

### ISSUE THREAD

**Issue by max-ostapenko** [Nu11u5/chromium-flags#2]
I found the platforms I needed, thanks.
And noticed there is also [iOS flags list](https://chromium.googlesource.com/chromium/src.git/+/main/ios/chrome/browser/flags/about_flags.mm) in a repository.

Maybe adding it will be helpful for someone else.

**Comment by Nu11u5** [comment]
Thanks for pointing this out.  Looks like the text values are [found here](https://chromium.googlesource.com/chromium/src.git/+/main/ios/chrome/browser/flags/ios_chrome_flag_descriptions.cc).  I'll look into incorporating those files into the scraper.

**Comment by Nu11u5** [comment]
Initial support for iOS flags added.
